### ISSUE TITLE
Displaying timestamps in original format

### ISSUE THREAD

**Issue by dahankzter** [jcasts/pjs#1]
I have a field that is a timestamp:

"modifiedDate" : 1431542421000,

However pjs displays it as such:

"modifiedDate": 1.391165814e+12,

Would it not be better to keep the original format?

**Comment by jcasts** [comment]
Good catch. That's a side effect of Go's parsing of JSON numbers when omitting a Go type. Easy enough to fix. :)

**Comment by jcasts** [comment]
Fixed in pjs-1.0.1
